services:
  - type: web
    name: smart-irrigation-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sis.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: MONGODB_URI
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "smart-irrigation-backend.onrender.com"
